#!/bin/bash

echo "🚀 Setting up Supabase Database for Teachers Club..."
echo ""
echo "📋 Steps to complete setup:"
echo ""
echo "1. 📖 Open your Supabase Dashboard:"
echo "   https://apovxgssuxjlraqauczl.supabase.co"
echo ""
echo "2. 🗄️ Navigate to SQL Editor (left sidebar)"
echo ""
echo "3. 📋 Copy the contents of 'supabase-migration.sql' file"
echo ""
echo "4. ▶️ Paste and run the SQL in the editor"
echo ""
echo "5. ✅ Once migration is complete, restart the dev server:"
echo "   npm run dev"
echo ""
echo "🔧 Your Supabase configuration:"
echo "   URL: https://apovxgssuxjlraqauczl.supabase.co"
echo "   Environment variables are set in .env.local"
echo ""
echo "📝 Test users will be created with these credentials:"
echo "   admin@teachersclub.com (admin)"
echo "   teacher@teachersclub.com (teacher)"  
echo "   student@teachersclub.com (student)"
echo "   moderator@teachersclub.com (moderator)"
echo ""
echo "🎯 After migration, comment deletion should work properly!"
echo ""
